index:
    path: /inicio
    controller: App\Controller\HomeControlerController::index

animales:
    path: /animales/{nombre}/{apellidos}
    controller: App\Controller\HomeControlerController::animales
    defaults: { nombre: 'eduard antonio', apellidos: 'colmenares hernandez' }
    requirements:
        nombre: '[a-zA-Z ]+'
        apellidos: '[a-zA-Z ]+'

redirigir:
    path: /redirigir
    controller: App\Controller\HomeControlerController::redirigir

animal_index:
    path: /animal/index
    controller: App\Controller\AnimalController::index

animal_save:
    path: /animal/save
    controller: App\Controller\AnimalController::save

animal_accion:
    path: /animal/{id}
    controller: App\Controller\AnimalController::animal

animal_update:
    path: /animal/update/{id}
    controller: App\Controller\AnimalController::update

animal_delete:
    path: /animal/delete/{id}
    controller: App\Controller\AnimalController::delete
